/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: streamer.proto */

#ifndef PROTOBUF_C_streamer_2eproto__INCLUDED
#define PROTOBUF_C_streamer_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _CloudServer CloudServer;
typedef struct _AddStreamerRequest AddStreamerRequest;


/* --- enums --- */


/* --- messages --- */

struct  _CloudServer
{
  ProtobufCMessage base;
  char *id;
  char *ip;
};
#define CLOUD_SERVER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cloud_server__descriptor) \
    , NULL, NULL }


struct  _AddStreamerRequest
{
  ProtobufCMessage base;
  char *username;
  char *password;
  CloudServer *server;
};
#define ADD_STREAMER_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&add_streamer_request__descriptor) \
    , NULL, NULL, NULL }


/* CloudServer methods */
void   cloud_server__init
                     (CloudServer         *message);
size_t cloud_server__get_packed_size
                     (const CloudServer   *message);
size_t cloud_server__pack
                     (const CloudServer   *message,
                      uint8_t             *out);
size_t cloud_server__pack_to_buffer
                     (const CloudServer   *message,
                      ProtobufCBuffer     *buffer);
CloudServer *
       cloud_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cloud_server__free_unpacked
                     (CloudServer *message,
                      ProtobufCAllocator *allocator);
/* AddStreamerRequest methods */
void   add_streamer_request__init
                     (AddStreamerRequest         *message);
size_t add_streamer_request__get_packed_size
                     (const AddStreamerRequest   *message);
size_t add_streamer_request__pack
                     (const AddStreamerRequest   *message,
                      uint8_t             *out);
size_t add_streamer_request__pack_to_buffer
                     (const AddStreamerRequest   *message,
                      ProtobufCBuffer     *buffer);
AddStreamerRequest *
       add_streamer_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   add_streamer_request__free_unpacked
                     (AddStreamerRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CloudServer_Closure)
                 (const CloudServer *message,
                  void *closure_data);
typedef void (*AddStreamerRequest_Closure)
                 (const AddStreamerRequest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cloud_server__descriptor;
extern const ProtobufCMessageDescriptor add_streamer_request__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_streamer_2eproto__INCLUDED */
