/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: streamer.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "streamer.pb-c.h"
void   cloud_server__init
                     (CloudServer         *message)
{
  static const CloudServer init_value = CLOUD_SERVER__INIT;
  *message = init_value;
}
size_t cloud_server__get_packed_size
                     (const CloudServer *message)
{
  assert(message->base.descriptor == &cloud_server__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cloud_server__pack
                     (const CloudServer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cloud_server__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cloud_server__pack_to_buffer
                     (const CloudServer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cloud_server__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CloudServer *
       cloud_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CloudServer *)
     protobuf_c_message_unpack (&cloud_server__descriptor,
                                allocator, len, data);
}
void   cloud_server__free_unpacked
                     (CloudServer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cloud_server__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   add_streamer_request__init
                     (AddStreamerRequest         *message)
{
  static const AddStreamerRequest init_value = ADD_STREAMER_REQUEST__INIT;
  *message = init_value;
}
size_t add_streamer_request__get_packed_size
                     (const AddStreamerRequest *message)
{
  assert(message->base.descriptor == &add_streamer_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t add_streamer_request__pack
                     (const AddStreamerRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &add_streamer_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t add_streamer_request__pack_to_buffer
                     (const AddStreamerRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &add_streamer_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AddStreamerRequest *
       add_streamer_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AddStreamerRequest *)
     protobuf_c_message_unpack (&add_streamer_request__descriptor,
                                allocator, len, data);
}
void   add_streamer_request__free_unpacked
                     (AddStreamerRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &add_streamer_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cloud_server__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CloudServer, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CloudServer, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cloud_server__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = ip */
};
static const ProtobufCIntRange cloud_server__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cloud_server__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CloudServer",
  "CloudServer",
  "CloudServer",
  "",
  sizeof(CloudServer),
  2,
  cloud_server__field_descriptors,
  cloud_server__field_indices_by_name,
  1,  cloud_server__number_ranges,
  (ProtobufCMessageInit) cloud_server__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor add_streamer_request__field_descriptors[3] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AddStreamerRequest, username),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AddStreamerRequest, password),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AddStreamerRequest, server),
    &cloud_server__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned add_streamer_request__field_indices_by_name[] = {
  1,   /* field[1] = password */
  2,   /* field[2] = server */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange add_streamer_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor add_streamer_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AddStreamerRequest",
  "AddStreamerRequest",
  "AddStreamerRequest",
  "",
  sizeof(AddStreamerRequest),
  3,
  add_streamer_request__field_descriptors,
  add_streamer_request__field_indices_by_name,
  1,  add_streamer_request__number_ranges,
  (ProtobufCMessageInit) add_streamer_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
